[package]
name = "advent_of_code_2023"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-format = "0.4.4"
num = "0.4.1"
itertools = "0.12.0"
rulinalg = "0.4.2"
rand = "0.8.5"